### ISSUE TITLE
Wrong tracknames in CREST2 mode

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#106]
Found two tracks yesterday, which have a wrong Name2 in the class_reference_points:
Algarve and Red Bull Ring GP
I have already checked these names in the past with CREST1 and SharedMemory pcars1 mode.
Either the names were updated in a Patch again, or the names are different in SharedMemory pcars1 and pcars2 mode.

**Comment by viper4gh** [comment]
ToDo:
1. Check if there is a difference between SharedMemory pcars1 and SharedMemory pcars2 mode in pcars2
2. Check all other new tracks again

**Comment by viper4gh** [comment]
There are differences between the two modes.
Main differences:
pcars1 mode <--> pcars2 mode
Grand Prix     <--> GP
Circuit of the Americas National_Circuit (blanks) <-->  Circuit_of_the_Americas National_Circuit  (underlines)

**Comment by viper4gh** [comment]
Old tracks are affected, too.
ToDo:
check all old tracks

**Comment by eckhchri** [comment]
Add a new attribute "AltNames" to RefPoints documented Issue #108 . So it is possible to give a track with a unique TrackID several Names. Can be used for Trackname-to.TrackID mapping

**Comment by viper4gh** [comment]
All Names checked and updated.
