### ISSUE TITLE
New Window for fiddling with refpoint values

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#111]
If devmode_tm is true, show a window with input fields which show the following values of the current used refpoint:
  refLat
  refLong
  rotation
  cor_r_Long
  cor_r_Lat
  cor_PosX_mul
  cor_PosY_mul

These values must be changable. That's the cause why these should be input fields. 
If you change one value and press enter, the change should be visible on the map.

**Comment by eckhchri** [comment]
Some basic implementations with https://github.com/eckhchri/pcars-ds-liveview/commit/d98fa2058ec9ee3178ddb12cb9520ad91e32328f

**Comment by viper4gh** [comment]
implemented
