### ISSUE TITLE
Convert aDrivers array to an Object with aDrivers array and other values

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#29]
Auf deutsch, sonst wirds zu kompliziert ;-)
Für das Updaten der Fahrerpunkte auf der Karte brauchen wir in relativ kleinen Intervallen alle Positionsdaten aller Fahrer. Zum Berechnen der Koordinaten ist aber außerdem die TrackID relevant.
Da wir aber nur einen HTTP-Request pro Intervall machen wollen und wir pro Abrage nur das Array aDrivers zurückgeben, haben wir bei jedem Driver die TrackID als various parameters hinterlegt.

Eine bessere Lösung wäre ein data Objekt zurückzugeben, das dann das aDrivers-Array und andere Variablen wie die TrackID enthalten kann.
data.aDrivers[]
data.TrackID
data.GridSize   ??

Im ersten Schritt müsste also über das aDrivers array ein data Objekt gestülpt werden.
D.h. überall wo aDrivers vorkommt, muss es dann quasi zu data.aDrivers werden.
-> index2.html, receive_ds_data.js, worker_driverdata.js
aDrivers -> aDrivers.data

Im zweiten Schritt müsste beim receive_ds_data die TrackID (und evtl. auch die GridSize, falls das abgefragt wird) ins neue Objekt data.TrackID geschrieben und dann überall auch so abgefragt werden.
-> receive_ds_data.js, index2.html
aDrivers.variousParameters.TrackId -> data.TrackID

Im dritten Schritt können dann die various parameters aus dem aDrivers Array und die dazugehörigen Aufrufe entfernt werden.
-> receive_ds_data.js, pcars_driver.js, index2.html (falls nach Schritt 2 da noch was übrig sein sollte),

**Comment by viper4gh** [comment]
Ergänzung:
Von der reinen Logik her sollte die Webseite nach jedem Schritt lauffähig sein. Somit kann man sich das etwas einteilen.
Weiterhin könnte man das data Objekt auch so aufbauen:
  data.aDrivers[]
  data.globals{}
Und dann 
  data.globals.TrackID
  data.globals.GridSize
...

**Comment by eckhchri** [comment]
Add new DS ReceiveMode "GETDSANDDRIVERDATA" combining GETDSDATA and GETDRIVERDATE. Reduce HTTP requests and worker threads.
