### ISSUE TITLE
driver table not correct sortable

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#42]
The columns Pos and Driver Name for example are not correct sortable. Other columns with simple numbers like the PosX and Sector are working. Lap times is also not fully correct.

**Comment by eckhchri** [comment]
Some fixes added via commit https://github.com/eckhchri/pcars-ds-liveview/commit/d1653eeedc03192c83a7b327ba381d0caed95d97
Not fully tested, but seems fine.

**Comment by viper4gh** [comment]
The index property prevents the correct sorting of driverposition.
index property deleted via commit https://github.com/eckhchri/pcars-ds-liveview/commit/e133df7d7a94df049f55b84b79128d7c67299e98
