### ISSUE TITLE
Add car description and number of laps to driver table

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#45]
It makes sense to know which driver uses which car.
Further in multiclass races the number of laps and also the car class is relevant.

**Comment by eckhchri** [comment]
**1. step:**
Add both parameters in PCARSDriver object with commit https://github.com/eckhchri/pcars-ds-liveview/commit/a3cc50317eaec1db961bec8178b890e2b74fe6b7
Not finally tested

**Comment by eckhchri** [comment]
2.  add Vehicle name Resolution with commit https://github.com/eckhchri/pcars-ds-liveview/commit/d509080cf5c2939c93b50041402a46038d8e1202
