### ISSUE TITLE
driver table not resetting on map change

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#49]
If you change to a new location in game, the map switches automatically, but the driver table has for example the old times from the last location.

**Comment by eckhchri** [comment]
Should be fixed in the past while change way of filling table.
In https://github.com/eckhchri/pcars-ds-liveview/commit/ca9911f7f458a3d5b67a16cbe88755dfc712ab05 
A change from DS to Demo mode also reset drivers table.
