### ISSUE TITLE
Marker jumping if ranking positions changing

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#52]
You see this problem during qualifying, if a car reaches the start/finish line and his ranking position changes.

[https://www.youtube.com/watch?v=gNqplLs6TKs](https://www.youtube.com/watch?v=gNqplLs6TKs)
You can see it beginning at ca. 3:30 min

**Comment by viper4gh** [comment]
Maybe issue #44 ist he same problem.

**Comment by viper4gh** [comment]
ds liveview Analyse jumping:
[https://www.youtube.com/watch?v=WKYMHvBADH0](https://www.youtube.com/watch?v=WKYMHvBADH0)

ds liveview Analyse jumping race:
[https://www.youtube.com/watch?v=khA_AUS3lLU](https://www.youtube.com/watch?v=khA_AUS3lLU)

ds liveview Analyse jumping transition0:
[https://www.youtube.com/watch?v=SScK-M2MXkw](https://www.youtube.com/watch?v=SScK-M2MXkw)

**Comment by viper4gh** [comment]
ds liveview Analyse jumping:
[https://www.youtube.com/watch?v=WKYMHvBADH0](https://www.youtube.com/watch?v=WKYMHvBADH0)
[Analyse_jumping.txt](https://github.com/eckhchri/pcars-ds-liveview/files/156288/Analyse_jumping.txt)

2:19 in video = 3:14.429 in enclosed data file and first example where driver on position 5 jumps to position 1
2:27 = 3:22.225  - second example: driver on pos 8 jumps to 3

Data seems ok during a jumping. Further the "transition 0" video from comment above shows no jumping markers. In result the transformWithEase function with the DisplayDuration time seems to be the problem.

Maybe it has something to do that we have a minimum DisplayDuration of 500ms, because the data from DS is only updated every 500ms. But in this case here we have 2-3 worker runs during the 500ms, where the transformWithEase function is triggered. What happens with an already running transformWithEase function?

Next tests:
- reduce the DisplayDuration with the slider to a duration which is lower than the time between a worker run
- higher the worker delay, that we have a time of ca. 500ms between the worker runs
- CREST mode, maybe higher the worker delay to better see if it happens

A general solution could be to check the data, compare it with the recent worker run data and prevent an update if the data is equal.
Or changing the worker_delay dynamically and synchronize it with the DS Update Rate.
But this depends on the next tests.

**Comment by viper4gh** [comment]
More Info about D3 Transitions:
[https://github.com/mbostock/d3/wiki/Transitions](https://github.com/mbostock/d3/wiki/Transitions)

Maybe the problem D3 internal.

**Comment by viper4gh** [comment]
disabled call of CleanupDriverObjects(_allDrivers)

https://www.youtube.com/watch?v=L1NeF5GADn4
At 2:05 min the position changing is beginning.
There is no jumping anymore, but the marker text update is not working.

**Comment by eckhchri** [comment]
Seems to be fixed fixed in commit https://github.com/eckhchri/pcars-ds-liveview/commit/efefdaa59f95a49f15f7daed2f40064161bf00bb
But only tested with demo data

**Comment by eckhchri** [comment]
Just for information from issue #56 : http://stackoverflow.com/questions/21843667/d3-change-text-label-when-data-updates

**Comment by eckhchri** [comment]
Fixed within commit https://github.com/eckhchri/pcars-ds-liveview/commit/7846565f38776e97a15873eb4f309883f1ca6528
- update labels on existing markers
- delete Ghorst markers from map

not finally tested

**Comment by eckhchri** [comment]
Effect did not occur  anymore.
