### ISSUE TITLE
Not all Vehicle IDs are converted to the Vehicle Name

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#54]
In the test case all Vehicle IDs with negative values were not converted. Maybe it has something to do with it.

![vehicleid_vehiclename_problem](https://cloud.githubusercontent.com/assets/13273234/13626873/faecf710-e5c5-11e5-9d09-77f8be6716d2.jpg)

**Comment by eckhchri** [comment]
First Update with commit https://github.com/eckhchri/pcars-ds-liveview/commit/08ebb361949ce2289f64b87f505ff74cb70ec4fc 
Ruf CTR3 SMS-R with negative vehicle ID works fine.
![20160309_pcars_unbenannt_vehiclenameconversionnegativeint_ruf](https://cloud.githubusercontent.com/assets/1454619/13643796/d4b83e8a-e622-11e5-8fd2-c311c83a23ea.PNG)

But still numbers within driver table.
It seem that not all vehicle IDs are included within hash.
![20160309_pcars_unbenannt_vehiclenameconversionnegativeint](https://cloud.githubusercontent.com/assets/1454619/13643905/6a13fc9e-e623-11e5-9de9-b56a1ecadc0b.PNG)

**Comment by eckhchri** [comment]
IDs not available in this case:
-2025231366
-384044277
