### ISSUE TITLE
CREST not working

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#76]
CREST v1 mode not working in pcars1 or pcars2.
Nothing happens if I switch to CREST mode.

following errors in console log:

Error if I drive alone:
Uncaught TypeError: Cannot set property '0' of undefined

Error if I drive with 10 AI:
Uncaught TypeError: Cannot set property '10' of undefined

**Comment by viper4gh** [comment]
![crest error](https://cloud.githubusercontent.com/assets/13273234/21906107/37066d8e-d90a-11e6-8bfa-4e242e6fd5c9.jpg)

**Comment by eckhchri** [comment]
First assumption is:      data.**driverlist**  array was not allocated as an array for this case

For "GETDEMODATA" and "GETDSANDDRIVERDATA" it was done within both cases separately.
**Solution:**  add following line at beginning of the script. So it is available for all cases.
  `data.driverlist 	=	[];` 

First fix uploaded with commit: https://github.com/eckhchri/pcars-ds-liveview/commit/1e4330e9afce3a6b1d883b08a58e3223c2a9d0bb
   
Demo-Mode works fine. DS and CREST not testetd yet.

**Comment by viper4gh** [comment]
The change solved the error in CREST mode, too.
But now only the map is correct initialized, there are no drivers, no points on map on no drivers in the driverstable, tested with 10 AI.
The data receiving from CREST API seems to work correct, but the driverlist don't gets the data.

![crest error](https://cloud.githubusercontent.com/assets/13273234/21928395/d277f9b0-d98a-11e6-8574-69315089d216.jpg)

**Comment by viper4gh** [comment]
Now in german ;-)

Der geht ganz normal in der ReceiveDSdata die for Schleife mit der Anzahl der Fahrer durch:
[https://github.com/eckhchri/pcars-ds-liveview/blob/master/receive_ds_data.js#L438](url)

Ich denke es gibt ein Problem bei der Zuweisung in die driverlist mit dem PCARSdriver Objekt an dieser Stelle:
[https://github.com/eckhchri/pcars-ds-liveview/blob/master/receive_ds_data.js#L449](url)

**Comment by eckhchri** [comment]
next fix in commit https://github.com/eckhchri/pcars-ds-liveview/commit/30e8509ec457ad46f4af40b1b61f8c958710ee63

Seems taht I used wrong array name to push drivers data. 
Same changes for mode GETCRESTDRIVERDATA and GETCREST2DRIVERDATA.

**Comment by viper4gh** [comment]
Perfect, now it is working.
Thanks for the fast support ;-)
