### ISSUE TITLE
drivertable not scrollable

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#80]
If there are to many drivers in the table ( for example more than 30 on a Full HD screen) you cannot see the entries after 30.
In result we need a max value for the table and a scrollbar if there is not enough space to show all entries.

**Comment by eckhchri** [comment]
Fixed in commit https://github.com/eckhchri/pcars-ds-liveview/commit/9af8b5fa93595ae12fa444ff1674295d02094f9b.

Change order of loading css files. pcars.css is now loaded after jqgrid.css. This make it possible to overwrite some CSS settings like overflow-x: hidden; to suppress X-scrollbar
