### ISSUE TITLE
table searching enhancement

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#90]
Currently the table searching has defaultSearching on cn=contains.
But if you search for the VehicleClass GT3 you get not only GT3, you get GT3X additionally.

Possible solution:
enable the searchOperator dropdown menu:
`jQuery("#DriverDataTable").jqGrid('filterToolbar', { stringResult: true, searchOnEnter: false, defaultSearch: "cn",  searchOperators: true });`

And add the searchoptions in the colModel:
`{name:'vehicleclass',width:60,sorttype:"text", searchoptions:{sopt:['cn','eq']}},`

info:
http://www.trirand.com/jqgridwiki/doku.php?id=wiki:toolbar_searching
http://www.trirand.com/jqgridwiki/doku.php?id=wiki:search_config
http://www.trirand.com/jqgridwiki/doku.php?id=wiki:search_config#colmodel_options

**Comment by eckhchri** [comment]
cn=contains will be the standard search algorithm. 
Changes could have impact in relation to visible/hide makrer depending on filter on the table.
