### ISSUE TITLE
Hide/Unhide marker depending on vehicle classes

### ISSUE THREAD

**Issue by viper4gh** [eckhchri/pcars-ds-liveview#94]
Implement a possibility to show only the marker of a specific vehicle class.
In best case hooked to the vehicle class filter of the driver table.

**Comment by eckhchri** [comment]
Extend enhancement request by combine filtering possibility within drivertable to hide driverobjects related to several values.
There is also an opacity level to hide objects in a smooth way instead a comple hiding. Available via DS settings dialog as a slider
